class Rnx < Formula
  desc "Command-line client for the Joblet job execution platform"
  homepage "https://github.com/ehsaniara/joblet-rnx"
  version "6.0.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ehsaniara/joblet-rnx/releases/download/v6.0.1/rnx-v6.0.1-darwin-arm64.tar.gz"
      sha256 "69fe96db0d9f24cb4b5618a9c97c8336af6f0530adb4a705b0555556a9db92bd"
    end
    on_intel do
      url "https://github.com/ehsaniara/joblet-rnx/releases/download/v6.0.1/rnx-v6.0.1-darwin-amd64.tar.gz"
      sha256 "419aac6244cac3b0efc2232c758a6b5b556a0122f6ca2ee8a4befd4293071f66"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ehsaniara/joblet-rnx/releases/download/v6.0.1/rnx-v6.0.1-linux-arm64.tar.gz"
      sha256 "d7615ee8b109c32372d0de5695231cda6711484a6b8c4801eeefb33734e3afce"
    end
    on_intel do
      url "https://github.com/ehsaniara/joblet-rnx/releases/download/v6.0.1/rnx-v6.0.1-linux-amd64.tar.gz"
      sha256 "d9a83d3d4c20f6167275e3eac5fbb4cc3ea7fe7072f8e598c3c88ea6b0c40d54"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "rnx-#{os}-#{arch}" => "rnx"
  end

  def caveats
    <<~EOS
      Copy a client config generated by your Joblet server into ~/.rnx:
        mkdir -p ~/.rnx
        scp user@joblet-server:/opt/joblet/config/rnx-config.yml ~/.rnx/

      Then verify the connection:
        rnx job list
    EOS
  end

  test do
    assert_match "rnx", shell_output("#{bin}/rnx --version")
  end
end
