class Rnx < Formula
  desc "Command-line client for the Joblet job execution platform"
  homepage "https://github.com/ehsaniara/joblet-rnx"
  version "6.0.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ehsaniara/joblet-rnx/releases/download/v6.0.2/rnx-v6.0.2-darwin-arm64.tar.gz"
      sha256 "0f35b840d990ad7a758369f3546de10cc50a522b0c529da51d6c71ee4e7e30da"
    end
    on_intel do
      url "https://github.com/ehsaniara/joblet-rnx/releases/download/v6.0.2/rnx-v6.0.2-darwin-amd64.tar.gz"
      sha256 "3e6b6b8e056b7ef50745d1ffe400527bc035f6b338dae18bbd4131674c4c3ea0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ehsaniara/joblet-rnx/releases/download/v6.0.2/rnx-v6.0.2-linux-arm64.tar.gz"
      sha256 "949ea83187aef531ce6a9c91342abb8014c5fe81e2896973b44fff153043c8bb"
    end
    on_intel do
      url "https://github.com/ehsaniara/joblet-rnx/releases/download/v6.0.2/rnx-v6.0.2-linux-amd64.tar.gz"
      sha256 "fa6ef65bc281a5545821440bc886e91d6557ba9a7e691bbd552671dfe5fc114b"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "rnx-#{os}-#{arch}" => "rnx"
  end

  def caveats
    <<~EOS
      Copy a client config generated by your Joblet server into ~/.rnx:
        mkdir -p ~/.rnx
        scp user@joblet-server:/opt/joblet/config/rnx-config.yml ~/.rnx/

      Then verify the connection:
        rnx job list
    EOS
  end

  test do
    assert_match "rnx", shell_output("#{bin}/rnx --version")
  end
end
