#!/bin/bash

# Regenerate Formula/rnx.rb for a published release.
# Usage: ./scripts/update-homebrew-formula.sh v6.0.0
#
# Fetches the release's checksums.txt and writes the formula with pinned
# URLs and sha256 values. Run after the release workflow has published the
# assets, then commit the updated formula through a PR.

set -e

VERSION="${1}"
if [ -z "$VERSION" ]; then
    echo "Usage: $0 <version>   (e.g. $0 v6.0.0)"
    exit 1
fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BASE="https://github.com/ehsaniara/joblet-rnx/releases/download/${VERSION}"

echo "Fetching checksums for ${VERSION}..."
CHECKSUMS=$(curl -fsSL "${BASE}/checksums.txt")

sha_for() {
    echo "$CHECKSUMS" | awk -v f="rnx-${VERSION}-$1.tar.gz" '$2 == f {print $1}'
}

DARWIN_ARM64=$(sha_for darwin-arm64)
DARWIN_AMD64=$(sha_for darwin-amd64)
LINUX_ARM64=$(sha_for linux-arm64)
LINUX_AMD64=$(sha_for linux-amd64)

for v in DARWIN_ARM64 DARWIN_AMD64 LINUX_ARM64 LINUX_AMD64; do
    [ -n "${!v}" ] || { echo "missing checksum for $v in checksums.txt"; exit 1; }
done

CLEAN_VERSION="${VERSION#v}"

cat > "$ROOT/Formula/rnx.rb" << EOF
class Rnx < Formula
  desc "Command-line client for the Joblet job execution platform"
  homepage "https://github.com/ehsaniara/joblet-rnx"
  version "${CLEAN_VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${BASE}/rnx-${VERSION}-darwin-arm64.tar.gz"
      sha256 "${DARWIN_ARM64}"
    end
    on_intel do
      url "${BASE}/rnx-${VERSION}-darwin-amd64.tar.gz"
      sha256 "${DARWIN_AMD64}"
    end
  end

  on_linux do
    on_arm do
      url "${BASE}/rnx-${VERSION}-linux-arm64.tar.gz"
      sha256 "${LINUX_ARM64}"
    end
    on_intel do
      url "${BASE}/rnx-${VERSION}-linux-amd64.tar.gz"
      sha256 "${LINUX_AMD64}"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "rnx-#{os}-#{arch}" => "rnx"
  end

  def caveats
    <<~EOS
      Copy a client config generated by your Joblet server into ~/.rnx:
        mkdir -p ~/.rnx
        scp user@joblet-server:/opt/joblet/config/rnx-config.yml ~/.rnx/

      Then verify the connection:
        rnx job list
    EOS
  end

  test do
    assert_match "rnx", shell_output("#{bin}/rnx --version")
  end
end
EOF

echo "Formula/rnx.rb updated for ${VERSION}"
echo "  darwin-arm64 ${DARWIN_ARM64}"
echo "  darwin-amd64 ${DARWIN_AMD64}"
echo "  linux-arm64  ${LINUX_ARM64}"
echo "  linux-amd64  ${LINUX_AMD64}"
echo "Commit the change through a PR."
